### ISSUE TITLE
Import notebook from local computer.

### ISSUE THREAD

**Issue by charlesjavelona** [deepkalilabs/cosmicnotebook#6]
Given that many folks already have their own local projects - we should have a way to import their project into our system so that they don't have to redo their project.

**Comment by shikhar394** [comment]
https://github.com/deepkalilabs/cosmicnotebook/pull/9 supports a short-term workaround. long-term we should make our notebooks compatible with OG jupyter notebook. there's a lot of markdown stuff we don't support atm. something to keep in mind as we get to notebook feature parity.

**Comment by charlesjavelona** [comment]
#7. Closed

**Comment by charlesjavelona** [comment]
#7 Imported.
